// Fast component-by-component (CBC) construction of rank-1 lattice rules.
//
// A rank-1 lattice with prime size N and generator g in {1, ..., N-1}^d has
// points frac(k g / N), k = 0..N-1. Its quality is measured by the weighted
// Korobov worst-case error (smoothness alpha = 2), which for product weights
// gamma_j is
//
//     e^2(g) = -1 + (1/N) sum_{k=0..N-1} prod_{j=1..d}
//                  (1 + gamma_j B2(frac(k g_j / N))),
//
// with the Bernoulli polynomial B2(x) = x^2 - x + 1/6 (the constant factor
// 2 pi^2 is absorbed into the weights). The weights 1, 1, 0.8, 0.8^2, ...
// follow SciPy and make later coordinates matter less.
//
// CBC fixes g_1 = 1 and then, for s = 2..d, chooses g_s to minimize e^2 with
// g_1..g_{s-1} held fixed. Keeping the products p(k) over the fixed
// coordinates, each step must evaluate
//
//     sum_k p(k) (1 + gamma_s B2(frac(k g / N)))   for every candidate g,
//
// which costs O(N^2) directly. Nuyens and Cools observed that the nonzero
// residues mod a prime N form a cyclic group generated by a primitive root
// r: writing g = r^j and k = r^-i turns k g into r^(j-i), so the candidate
// sums are a cyclic convolution of p with B2, computed by FFT in
// O(N log N). Because B2(x) = B2(1 - x) and p(k) = p(N - k), only the
// (N - 1) / 2 residues up to N / 2 are needed ("folding").
//
// Sources:
// - D. Nuyens and R. Cools, "Fast algorithms for component-by-component
//   construction of rank-1 lattice rules in shift-invariant reproducing
//   kernel Hilbert spaces", Math. Comp. 75 (2006) 903-920,
//   https://doi.org/10.1090/S0025-5718-06-01785-6
// - SciPy's _cbc_lattice, from which this is ported:
//   https://github.com/scipy/scipy/blob/main/scipy/stats/_qmvnt.py

#include "mvn_moments/detail/lattice.hpp"

#include <algorithm>
#include <cmath>
#include <complex>
#include <cstdint>
#include <unsupported/Eigen/FFT>
#include <vector>

#include "mvn_moments/detail/primes.hpp"

namespace mvn::detail {
namespace {
// Relative gap below which CBC criterion values count as equal.
constexpr double kTieTolerance = 1e-12;

// Zero if no prime is found.
std::uint64_t LargestPrimeAtMost(std::uint64_t target)
{
    for (std::uint64_t step = 0; step + 2 <= target; ++step) {
        if (IsPrime(target - step)) {
            return target - step;
        }
    }

    return 0;
}

// Distinct prime factors in increasing order.
std::vector<std::uint64_t> PrimeFactors(std::uint64_t n)
{
    std::vector<std::uint64_t> factors;
    for (std::uint64_t divisor = 2; divisor <= kMaxDivisor; ++divisor) {
        if (divisor * divisor > n) {
            break;
        }
        if (n % divisor != 0) {
            continue;
        }

        factors.push_back(divisor);
        // A 64-bit value has at most 64 repeated prime factors.
        for (int power = 0; power < 64; ++power) {
            if (n % divisor != 0) {
                break;
            }
            n /= divisor;
        }
    }
    if (n > 1) {
        factors.push_back(n);
    }

    return factors;
}

// base^exponent mod modulus by binary exponentiation: square the base for each
// exponent bit and multiply it in where the bit is set.
std::uint64_t PowerMod(std::uint64_t base, std::uint64_t exponent,
                       std::uint64_t modulus)
{
    std::uint64_t result = 1;
    base %= modulus;
    for (int bit = 0; bit < 64; ++bit) {
        if (exponent == 0) {
            break;
        }
        if (exponent & 1) {
            result = result * base % modulus;
        }
        base = base * base % modulus;
        exponent >>= 1;
    }

    return result;
}

// Smallest r whose powers r^0..r^(p-2) run through every nonzero residue mod
// p. The order of r divides p - 1, so r is primitive exactly when
// r^((p-1)/q) != 1 for each prime factor q of p - 1. Zero if the search
// exhausts its bound.
std::uint64_t PrimitiveRoot(std::uint64_t prime)
{
    const auto factors = PrimeFactors(prime - 1);
    for (std::uint64_t root = 2; root < prime; ++root) {
        bool primitive = true;
        for (const auto factor : factors) {
            if (PowerMod(root, (prime - 1) / factor, prime) == 1) {
                primitive = false;
                break;
            }
        }
        if (primitive) {
            return root;
        }
    }

    return 0;
}

// Smallest power of two that is at least n; n is below 2^33.
std::size_t PowerOfTwoAtLeast(std::size_t n)
{
    std::size_t length = 1;
    for (int bit = 0; bit < 64; ++bit) {
        if (length >= n) {
            break;
        }
        length <<= 1;
    }

    return length;
}
}  // namespace

Status CbcLattice(std::size_t dimensions, std::uint64_t target_points,
                  Lattice& lattice)
{
    lattice = Lattice();
    if (target_points < 3 || target_points >= kMaxLatticePoints) {
        return Status::kInvalidInput;
    }

    const auto points = LargestPrimeAtMost(target_points);
    if (points == 0) {
        return Status::kInvalidInput;
    }
    lattice.points = points;
    if (dimensions == 0) {
        return Status::kOk;
    }

    // Generators come from the multiplicative group modulo N, folded to the
    // half-range by symmetry; kernel holds the Korobov kernel there.
    const std::uint64_t n = lattice.points;
    const std::size_t m = (n - 1) / 2;
    lattice.generator.assign(dimensions, 1);
    if (m == 1) {
        // N = 3 leaves 1 as the only candidate; skip a length-1 FFT, which
        // Eigen's kissfft backend does not support.
        return Status::kOk;
    }

    const auto root = PrimitiveRoot(n);
    if (root == 0) {
        lattice = Lattice();
        return Status::kInvalidInput;
    }
    std::vector<std::uint64_t> folded(m);
    std::vector<double> kernel(m);
    std::uint64_t power = 1;
    for (std::size_t j = 0; j < m; ++j) {
        folded[j] = std::min(power, n - power);
        const double x = static_cast<double>(folded[j]) / n;
        kernel[j] = x * x - x + 1.0 / 6;
        power = power * root % n;
    }

    // Cyclic convolutions use zero-padded power-of-two FFTs, then fold the
    // linear convolution, which keeps every transform length fast.
    const auto length = PowerOfTwoAtLeast(2 * m - 1);
    Eigen::FFT<double> fft;
    std::vector<std::complex<double>> padded(length), kernel_spectrum;
    for (std::size_t j = 0; j < m; ++j) {
        padded[j] = kernel[j];
    }
    fft.fwd(kernel_spectrum, padded);

    std::vector<double> product(m, 1.0);
    std::vector<std::complex<double>> spectrum, linear;
    std::vector<double> cyclic(m);
    std::size_t best = 0;
    for (std::size_t s = 1; s < dimensions; ++s) {
        // Product weights gamma = 1, 1, 0.8, 0.8^2, ... as in SciPy.
        const double weight = s == 1 ? 1.0 : std::pow(0.8, s - 2);
        for (std::size_t j = 0; j < m; ++j) {
            product[j] *= 1.0 + weight * kernel[(best + m - j) % m];
        }

        std::fill(padded.begin(), padded.end(), 0.0);
        for (std::size_t j = 0; j < m; ++j) {
            padded[j] = product[j];
        }
        fft.fwd(spectrum, padded);
        for (std::size_t j = 0; j < length; ++j) {
            spectrum[j] *= kernel_spectrum[j];
        }
        fft.inv(linear, spectrum);

        for (std::size_t k = 0; k < m; ++k) {
            cyclic[k] =
                linear[k].real() + (k + m < length ? linear[k + m].real() : 0);
        }

        // Minimize the worst-case error. Exact ties (e.g. a generator and its
        // modular inverse at s = 1) differ only by FFT rounding, so treat
        // near-equal values as ties and keep the smallest generator. SciPy
        // breaks these ties by rounding noise instead.
        const double smallest = *std::min_element(cyclic.begin(), cyclic.end());
        const double tie = smallest + kTieTolerance * std::abs(smallest);
        best = m;
        for (std::size_t k = 0; k < m; ++k) {
            if (cyclic[k] <= tie && (best == m || folded[k] < folded[best])) {
                best = k;
            }
        }
        lattice.generator[s] = folded[best];
    }

    return Status::kOk;
}
}  // namespace mvn::detail
